### ISSUE TITLE
Module 9 Lab, Exercise 9 task 4

### ISSUE THREAD

**Issue by tbkobberoe** [MicrosoftLearning/20697-2-DeployingManagingWindows10#12]
pt. 4: 
OneDrive For Business is now called OneDrive Desktop

pt.14 Select Add group, and then select Assignment type Available.

15 Click Included Groups, then Select Groups To Include

16Type Windows Devices, and select the group and click Select.
17 Click OK, twice, then Save
This is also applicable for Lab Answer Key

**Comment by skukrika** [comment]
Thank you for the report! I implemented all the changes you suggested in Mod 9 lab and LAK.

  Slavko
