### ISSUE TITLE
Module 10 lab B Exercise 1 task 1 pt. 1

### ISSUE THREAD

**Issue by tbkobberoe** [MicrosoftLearning/20697-2-DeployingManagingWindows10#13]
Remove the 2 * (asterisks) in *odopen://sync?useremail=Adam@*<YourInitials><MMDDYY>outlook.onmicrosoft.com

**Comment by itbland** [comment]
If you use Pandoc to convert the md into docx (per instructions) those extra \*'s are formatting marks (Sadly, Pandoc md syntax and the web md syntax is different, so you see them on the web page.) Hopefully, they'll approve a newer version of Pandoc and we'll get better formatting.

**Comment by skukrika** [comment]
Hello all!

  As itbland explained, asteriks are used for formating the document and they are removed when you run Pandoc to create lab instructions in Word format.

  I hope that with this clarification issue can be considered resolved and if there is no objections, I'll close this thread in few days.

  Slavko
