### ISSUE TITLE
Lab 9, Exercise 1, Task 5

### ISSUE THREAD

**Issue by xgyrosx** [MicrosoftLearning/20697-2-DeployingManagingWindows10#14]
Syncing Abbi's account won't work without these steps:

1. You have to select 'MDM Authority' to Intune on Azure portal -> All Services ->  Microsoft Intune -> Device Enrollment -> (select on the right side)

2. Furthermore, you have to login as local administrator on LON-CL3 and connect the client to Azure AD with Abbi's account.

**Comment by skukrika** [comment]
Hello xgyrosx!

  You are correct, both steps that you mentioned must be performed before you (Abbi) will be able to install assigned apps through Intune (which is done in Mod 9, Lab A, Exercise 1, Task 5). But if students follow instructions carefully, both those tasks are already performed in Lab 7:

1. Set MDM authority to Intune: students configure this in Mod 7, Lab A, Exercise 3, Task 1 (Configure Azure AD for automatic device enrollment).

2. Sign in to LON-CL3 as local administrator (Admin) and connect the client to Azure AD with Abbi's account: students configure this in Mod 7, Lab A, Exercise 3, Task 2 (Join a Windows 10 device to Azure AD, and enroll it in Intune).

  Regards
        Slavko

**Comment by skukrika** [comment]
I'm closing this issue, as I hope that previous reply provided clarification and pointer to the lab where students should perform required tasks that xgyrosx pointed out.

  Regards
             Slavko
