### ISSUE TITLE
Revision Suggestions for 20697-2

### ISSUE THREAD

**Issue by XtremeMichaelRogers** [MicrosoftLearning/20697-2-DeployingManagingWindows10#16]
Hi All, 
I just finished a run through of this lab series and I wanted to share a couple of revision suggestions that I had.  

In multiple areas through the lab the user creates groups in Microsoft Azure, the Lab Manual and Answer Key refer to "Users and Groups" as the section where this happens, but this appears to have ben worked out into two different areas in Azure, not really confusing, but a minor edit to consider.  More important is that sometime after the instructions here were written a new required field in creating groups in Azure was added, the user must select a group type (O365 or Security) and this information is not specified in the manual and can have an impact on the function of the lab.  

In Module 6 the user is working in O365 to enable MDM, but the instructions in the Lab Manual and Lab Answer Key appear to be out of date, the functions they describe are present, but have moved or in many cases been reworked so the UI is quite different from what is described with new required fields and navigation challenges that are not in the Lab Answer Key.  

In Module 11 the user is using nested virtualization in LON-CL1 to create and manage a couple of VMs (VM1 and VM2).  LON-CL1 does not appear to have the necessary resources, even after doubling the memory for the LON-CL1 VM, to run these without grinding to a halt.  Increasing the number of CPU cores in LON-CL1 when you double the memory in Task 1, Step 14 in the Answer Key enables the user to create, manage and work in the nested VMs without running out of resources.  

Thank you for your consideration.

**Comment by skukrika** [comment]
Hello Michael!

  Thank you for the suggestions! I have updated instructions for Lab 3 and Lab 7, in which students are creating static/assigned and dynamic user groups to include information to select Security group type. This selection was added after labs were developed and one of the benefits of this GitHub model is that lab instructions can be updated when needed, based on the suggestions and feedback.

  I also updated instructions for Lab 6 - I hope that instructions on how to enable MDM and how to create DLP policy are accurate again. I'm aware that there is still issue with obtaining trial Office 365 Enterprise E3 subscription (credit card is required), but Microsoft Learning will have to way to mitigate this requirement. If you (or any other trainer) will find any additional incorrect instructions in the lab, please feel free to report them or create pull request!

  Regarding Lab 11 suggestions, I verified that LON-CL1 VM is initially configured with 2GB RAM and 1 processor and in the lab students are instructed to increase memory to 4GB. With such configuration I was able te perform Lab 11 without any issue (my physical host was running Windows Server 2016), but I agree that it makes sense to provide additional virtual processor to LON-CL1. I'll probably include steps in Lab 11 for students to increase number of processors in LON-CL1 to 2.

  Regards and thank you for the suggestions!
        Slavko

**Comment by WynandWarren** [comment]
Was this for version B or C of the course?

**Comment by XtremeMichaelRogers** [comment]
Hi WynandWarren,
I was running the C version of the course.

**Comment by WynandWarren** [comment]
Hi,

Thank you for the assistance. I was asking because I noticed there was no lab instructions in the version C book. I managed to find those steps here on GitHub after reading your reply.

Once again thanks for your assistance guys

**Comment by skukrika** [comment]
As all the suggestions are implemented and there is no further discussion, I'm closing this thread. If anyone has additional comments/suggestions regarding that, thread can be reopened.

Slavko
