### ISSUE TITLE
Mod 04 Lab & LAK, ScanState syntax quibble

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20697-2-DeployingManagingWindows10#4]
While "**/ue:\*\\\* /ui:adatum\vera**" works, to be consistent with the documentation at [ScanState Syntax - Using the options together](https://docs.microsoft.com/en-us/windows/deployment/usmt/usmt-scanstate-syntax#using-the-options-together) it should be changed to "**/ue:\* /ui:adatum\vera**"

**Comment by skukrika** [comment]
Thank you for the suggestion! I updated ScanState syntax in Mod 4 Lab and LAK.

  Slavko
