### ISSUE TITLE
Which Pandoc version is correct?

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/20697-2-DeployingManagingWindows10#5]
[MCT Guide](https://github.com/MicrosoftLearning/20697-2-DeployingManagingWindows10/blob/master/20697-2C%20Github%20User%20Guide%20for%20MCTs.md) says 

> Pandoc version 1.19.2

Prerequisites in the[ Readme in the Build folder](https://github.com/MicrosoftLearning/20697-2-DeployingManagingWindows10/blob/master/Build/README.md) says 

> Pandoc 1.13.2 

(It makes a difference when trying to correct formatting problems in the markdown)

**Comment by StanReimer** [comment]
Hi Eric,

I will change the Readme to 1.19.2, unless if this causes additional formatting errors. What version are you using? Thanks for fixing up so many issues, I will make sure we catch these before release next time.

Stan

**Comment by itbland** [comment]
I switched back to 1.13.2 for this class. I will go back to 1.19.2 and re-evaluate the formatting. Thanks.
