### ISSUE TITLE
Lab 8 Ex 2, won't work

### ISSUE THREAD

**Issue by DavidvGe** [MicrosoftLearning/20697-2-DeployingManagingWindows10#8]
It's not possible to generate a device specific id, as the virtual environment has the same device specific id for LON-CL5, hence when you try to add the device to the "Microsoft store for Business" you'll get the error message stating that the device has already been added to another tenancy and cannot be added again.

Must have worked for the first person who did the lab, but won't ever work again. Rather than LON-CL5 being included in the lab image, I think if students have to add this as a new VM, before imaging it in Lab 02, this should resolve this issue.

**Comment by StanReimer** [comment]
Hi David,

When we shipped the course, we did not provide a LON-CL5, it is created by using script which creates the VM with a unique ID. Is LON-CL5 precreated in your lab? Could you provide some details on your lab environment so we can provide a work around? Thanks

**Comment by itbland** [comment]
Stan,
I don't have a lab running currently to test this issue, but we use Lab On Demand Systems labs. When a student starts the labs, they are presented with a HV-Host machine and the VMs are already created.

**Comment by StanReimer** [comment]
I will connect with LODs to let them know what the issue is and see if they can work around it.

**Comment by tbkobberoe** [comment]
In my organization we create the whole setup including running the Importvirtualmachine script on 1 reference computer, then capture that image and deploy to the students PC's, as I believe many other training providers do. In that case the Device serial number will be the same for all LON-CL5s. A workaround would be to create a new VM from the lon-cl5 VHD file, either before course start or as part of the lab

**Comment by swthibodeau** [comment]
I wanted to follow up on this thread to confirm that creating a new VM from scratch addressed the AutoPilot issue with LON-CL5 in the Lab On Demand systems. I made a VM called LON-CL6, and used the auto unattend and Win 10 Eval.iso to install the system. Then logged on as the local admin, ran the PS scripts and copied the csv file to the network share on LON-DC1 as directed, Finally, I sysprepped LON-CL6. I hope that helps!

**Comment by skukrika** [comment]
Windows AutoPilot uses information about computer hardware, including hardware ID, to link the computer to appropriate Azure AD tenant; this enables you to have custom sign-in screen and that correct AutoPilot deployment profile is used.

  Hardware information of Hyper-V virtual machine is generated when virtual machine is created. If you import virtual machine or clone Hyper-V host, virtual machine hardware id is preserved, which caused error mentioned in this thread.

  To avoid the issue, LON-CL5 is created from scratch by 20697-2C setup script (20697-2C_ImportVirtualMachines.ps1); LON-CL5 is blank virtual machine anyway. It is expected that setup script will be run on all students computers, before every 20697-2C delivery. If this is not the case, you should recreate LON-CL5 for each 20697-2C redelivery.

  Regards
        Slavko
